name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libraylib-dev
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure project
      run: |
        cd build
        cmake ..
        
    - name: Build project and tests
      run: |
        cd build
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ./EpiGimpTests --gtest_filter=-BasicTest* --gtest_output=xml:test_results.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/test_results.xml
        
    - name: Display test summary
      if: always()
      run: |
        cd build
        echo "=== Test Results Summary ==="
        if [ -f test_results.xml ]; then
          # Extract test count from XML
          total_tests=$(grep -o 'tests="[0-9]*"' test_results.xml | grep -o '[0-9]*' | head -1)
          failed_tests=$(grep -o 'failures="[0-9]*"' test_results.xml | grep -o '[0-9]*' | head -1)
          echo "Total tests: $total_tests"
          echo "Failed tests: $failed_tests"
          if [ "$failed_tests" = "0" ]; then
            echo "✅ All tests passed!"
          else
            echo "❌ Some tests failed!"
            exit 1
          fi
        else
          echo "❌ Test results file not found!"
          exit 1
        fi